# Generated by Django 2.0.4 on 2018-04-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180424_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='laanguage',
            new_name='language',
        ),
    ]
